### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by aapJoysakoi** [Avdhesh-Varshney/Chanakya-Niti#92]
There's a typo in the title of Episode 2. It's written Gulami "sea" mukti instead of Gulami "say" mukti.

**Comment by Avdhesh-Varshney** [comment]
@shivan2004 go ahead.

**Comment by aapJoysakoi** [comment]
Wait a second! I RAISED THE ISSUE. 🤷‍♀️

**Comment by Trident09** [comment]
@Avdhesh-Varshney this makes a very bad impression on you, seeing that someone is finding an issue and you are assigning that to someone else

The issuer may not know the norms of open source contributions but as this is a beginner project yo should keep this in mind so that beginners should have a better environment to learn

**Comment by shivan2004** [comment]
@Avdhesh-Varshney can you tag this issue with gssoc with any level

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney this makes a very bad impression on you, seeing that someone is finding an issue and you are assigning that to someone else
> 
> The issuer may not know the norms of open source contributions but as this is a beginner project yo should keep this in mind so that beginners should have a better environment to learn

@aapJoysakoi i have already assigned 1 issue to you. And in guidelines, i have mentioned that any contributor can raise atmost 1 issue at a time. Until and unless it is not solved. Don't raise another issue.

**Comment by shivan2004** [comment]
@aapJoysakoi I am not the one who raised the issue, but i was assigned to solve this issue
